### ISSUE TITLE
Serve locally instead of on Github?

### ISSUE THREAD

**Issue by bmp** [ikoamu/publish-org-roam-ui#15]
Hello and thank you for putting in the work to do this. I would like to check if it is possible to deploy/serve locally almost similar to org-roam-ui instead of onto Github. There are a couple of reasons I ask for this,
1. I tend to use org-roam-ui as a means of presentation nowadays, but when I wish to jump to a node through the browser, the lack of search means I need to switch to Emacs and then switch back to the browser. The search you have provided is a boon for this too.
2. Additionally, I have some notes that I would rather not have published externally, they are only for me to view (on the go as well). Therefore, I wish to publish it behind a simple .htaccess or a similar very elementary method. In order to do so, it would be nice to decouple it from publishing to github.

**Comment by ikoamu** [comment]
Hi, if you don't want to make it public on github, try the following

1. manage your roam files in a private repository
2. set `deploy-to-pages` to false to disable deployment to GitHub Pages
```yaml
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: ikoamu/publish-org-roam-ui@main
        with:
          org-roam-db-filename: <org-roam-filename>.db
          deploy-to-pages: false # 👈
```
4. download the artifacts generated by the GitHub Actions
![CleanShot 2024-06-11 at 23 45 09@2x](https://github.com/ikoamu/publish-org-roam-ui/assets/38206334/72bd5dc7-e46f-464f-ab0a-5bff05ecedfa)

This allows you to generate resources for your site without having to publish pages.
