### ISSUE TITLE
Add style for table and inline code

### ISSUE THREAD

**Issue by Thysrael** [ikoamu/publish-org-roam-ui#2]
org-roam-ui doesn't seem to have sytle configured for table and code, so I added the following code to any css file in the path `/org-roam-ui/out/_next/static/css/`.

```css
table {
    border-style: hidden;
}

th, tr, td {
    padding: 0px 4px;
    border-width: 1px;
    border-color: gray;
    border-style: dashed;
}

code.inline-code, code.inline-verbatim {
    border-radius: 5px;
    border: 1px solid #BCBEC0;
    padding: 2px;
}
```

It has the following effects:

table

![roam2](https://github.com/ikoamu/publish-org-roam-ui/assets/72613958/b64a8b4a-cc24-4e93-b6dd-2e47415cbd00)

code

![roam1](https://github.com/ikoamu/publish-org-roam-ui/assets/72613958/da033199-2af5-4203-9587-d141737dd95d)

Can you add this to your fork's org-roam-ui? I can also accept that you don't have to make any changes, because the way I do it, I modify the `out` folder directly, without modifying the source code. Or maybe you want to be as consistent as possible with upstream. I fully understand and respect your decision!

Thank you for maintaining this action!
