### ISSUE TITLE
Headers startup folded

### ISSUE THREAD

**Issue by sherlockes** [ikoamu/publish-org-roam-ui#27]
Is it possible to configure headers to appear folded by default?

Thsk

**Comment by ikoamu** [comment]
@sherlockes 
Hello. I apologize for the delayed response.
I've attempted an implementation, so please check it out.
Try generating the page by setting the yaml configuration as follows:
```yaml
      ...
      uses: ikoamu/publish-org-roam-ui@main # Use @main
        with:
          default-section-open: false # 👈
          ...
```
