### ISSUE TITLE
LaTeX not rendering correctly

### ISSUE THREAD

**Issue by michaelneuper** [ikoamu/publish-org-roam-ui#34]
Here is how LaTeX looks when running `org-roam-ui` locally:

<img width="500" alt="Screenshot 2024-11-19 at 22 13 14" src="https://github.com/user-attachments/assets/f01f56d6-878f-41a4-acad-68f1d24fe6a3">

Compared to the published version with `publish-org-roam-ui`:

<img width="500" alt="Screenshot 2024-11-19 at 22 11 49" src="https://github.com/user-attachments/assets/bab78b18-d034-49de-9bde-e8dc1e5d91c5">

**Comment by michaelneuper** [comment]
Upon investigating further, it seems that KaTeX is not finding the fonts.
From the network tab:
```
downloadable font: download failed (font-family: "KaTeX_Main" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://notes.michaelneuper.com/_next/static/css/_next/static/media/KaTeX_Main-Regular.0462f03b.woff2 
```

It seems that `/_next/static/css/1a8641ed10d4498c.css` is the file requesting the fonts, for example:
``` css
@font-face {
  font-family:KaTeX_Main;
  src:url(_next/static/media/KaTeX_Main-Regular.0462f03b.woff2) format("woff2"),
  url(_next/static/media/KaTeX_Main-Regular.7f51fe03.woff) format("woff"),
  url(_next/static/media/KaTeX_Main-Regular.b7f8fe9b.ttf) format("truetype");
  font-weight:400;
  font-style:normal
}
```

It looks like `/_next/static/css/1a8641ed10d4498c.css` is using the relative path `_next/static/media/KaTeX_Main-Regular.0462f03b.woff2)`  instead of the absolute path `/_next/static/media/KaTeX_Main-Regular.0462f03b.woff2)` which is causing the fonts to not be found.
